#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_entete:
  path: /entete/{title}
  controller: App\Controller\ContentController::display
  defaults:
    title: 'Paramètre non passé'
